### ISSUE TITLE
[Bug]? - "Decode Entities" fails if a semicolon (;) is present anywhere in the file before the first Entity

### ISSUE THREAD

**Issue by ChrisMyersAI** [rdipardo/nppHTMLTag#7]
If a semicolon (;) is anywhere in the same document before the first (X/HT)ML entity that would be decoded, then no (X/HT)ML entities are decoded with the "Decode Entities" command.

Example:
This `[anything] &#x2026; &quot;`will normally decode to `[anything] … "`.

But this `; [anything] &#x2026; &quot;` will stay completely unchanged.

This appears to happen as soon as a single semicolon is present before the first entity regardless of other content before the first entity, file type, or syntax language selected.

This is using UTF-8 files on Notepad++ v8.6.9 (32-bit) with the Plugin Admin v1.4.4 of HTML Tag.

**Comment by ChrisMyersAI** [comment]
I made some edits to the src/Entities.cpp file which I believed would fix the issue: 
[Entities.cpp Changes.zip](https://github.com/user-attachments/files/17451281/Entities.cpp.Changes.zip)
 (Edited file with an HTML diff report)

However, before I made a new build to test that, I noticed that the version on GitHub was 1.5.0, it just hadn't been pushed to the plugin list yet.
Out of curiosity, I manually installed 1.5.0, and this bug does not appear to be present in that version. (So I guess the bug was probably in src/U_Entities.pas instead)

I'm providing my version of the Entities.cpp file anyway just in case it helps.

**Comment by rdipardo** [comment]
Thanks for confirming that v1.5.0 resolves the issue.

In previous plugin versions, the entity decoder searched for the semi-colon from the start of the whole selection range [^1], and failed because the semi-colon did not come *after* the `&`:

https://github.com/rdipardo/nppHTMLTag/blob/85442c31723d40fc13c24913ac1ac0e68c84ff99/src/U_Entities.pas#L237-L241

In [the current version], the search for the semi-colon *begins* after the `&` as it logically should:

https://github.com/rdipardo/nppHTMLTag/blob/2426a1a7b4a09c670c75b782d944e3d53a63d382/src/Entities.cpp#L70-L74

[^1]: The Pascal code *would* have been correct if it used [PosEx] instead, i.e., ``PosEx(';', Text, CharIndex)``


[the current version]: https://github.com/rdipardo/nppHTMLTag/releases/tag/v1.5.1
[0]: https://bitbucket.org/rdipardo/htmltag/downloads/
[1]: https://github.com/rdipardo/nppHTMLTag/commit/85442c31723d40fc13c24913ac1ac0e68c84ff99
[PosEx]: https://www.freepascal.org/docs-html/rtl/strutils/posex.html

**Comment by rdipardo** [comment]
This issue is fixed as of version 1.5.0, available in [Plugins Admin] starting with Notepad++ [8.7.1].

[Plugins Admin]:https://npp-user-manual.org/docs/plugins/#install-using-plugins-admin
[8.7.1]:https://notepad-plus-plus.org/downloads/v8.7.1
